name: "Check and publish to NPM"

on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Check
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - name: publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npm i -g pnpm
          pnpm install --no-frozen-lockfile
          pnpm build
          pnpm release
